services:
  knyk.payum_dotpay_sylius.gateway_factory.dotpay:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments:
      - Knyk\Payum\Dotpay\Factory\DotpayGatewayFactory
    tags:
      - { name: payum.gateway_factory_builder, factory: dotpay }
  
  Knyk\Payum\Dotpay\Form\Type\SyliusGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: dotpay, label: Dotpay }
      - { name: form.type }
