services:
  knyk.dotpay_sylius.gateway_factory.dotpay:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments:
      - Knyk\SyliusDotpayPlugin\Factory\DotpayGatewayFactory
    tags:
      - { name: payum.gateway_factory_builder, factory: dotpay }

  Knyk\SyliusDotpayPlugin\Form\Type\SyliusGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: dotpay, label: Dotpay }
      - { name: form.type }
