services:
  knyk.dotpay_sylius.gateway_factory.dotpay:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments:
      - Knyk\SyliusDotpayPlugin\Factory\DotpayGatewayFactory
    tags:
      - { name: payum.gateway_factory_builder, factory: dotpay }
  
  Knyk\SyliusDotpayPlugin\Form\Type\SyliusGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: dotpay, label: Dotpay }
      - { name: form.type }
  
  Knyk\SyliusDotpayPlugin\Formatter\MoneyFormatter:
  Knyk\SyliusDotpayPlugin\Factory\HttpRequestFactory:
  Knyk\SyliusDotpayPlugin\Provider\ControlProvider:
  
  Knyk\SyliusDotpayPlugin\Factory\ActionDataFactory:
    arguments:
      $moneyFormatter: '@Knyk\SyliusDotpayPlugin\Formatter\MoneyFormatter'
      $paymentDescriptionProvider: '@sylius.payment_description_provider'
      $controlProvider: '@Knyk\SyliusDotpayPlugin\Provider\ControlProvider'
  
  Knyk\SyliusDotpayPlugin\Action\CaptureAction:
    public: true
    arguments:
      $actionDataFactory: '@Knyk\SyliusDotpayPlugin\Factory\ActionDataFactory'
    tags:
      - { name: payum.action, factory: dotpay, alias: payum.action.capture }
  
  Knyk\SyliusDotpayPlugin\Action\StatusAction:
    public: true
    arguments:
      $httpRequestFactory: '@Knyk\SyliusDotpayPlugin\Factory\HttpRequestFactory'
    tags:
      - { name: payum.action, factory: dotpay, alias: payum.action.status }

  Knyk\SyliusDotpayPlugin\Action\NotifyAction:
    public: true
    arguments:
      $moneyFormatter: '@Knyk\SyliusDotpayPlugin\Formatter\MoneyFormatter'
      $httpRequestFactory: '@Knyk\SyliusDotpayPlugin\Factory\HttpRequestFactory'
      $actionDataFactory: '@Knyk\SyliusDotpayPlugin\Factory\ActionDataFactory'
    tags:
      - { name: payum.action, factory: dotpay, alias: payum.action.notify }
